vm_list_dict = {
  "region": {"aws": {},
             "azure": {},
             "title": "Region"},
  "monitoring_state": {"aws": {"key": ["Monitoring", "State"], },
                       "azure": {},
                       "title": "Monitoring State"},
  "public_dns_name": {"aws": {"key": ["PublicDnsName"]},
                      "azure": {},
                      "title": "Public DNS"},
  "state": {"aws": {"key": ["State", "Name"]},
            "azure": {},
            "title": "State"},
  "ebsoptimized": {"aws": {"key": ["EbsOptimized"]},
                   "azure": {},
                   "title": "EBS Optimized"},
  "launch_time": {"aws": {"key": ["LaunchTime"]},
                  "azure": {}, "title":
                    "Launch Time"},
  "public_ip_address": {"aws": {"key": ["PublicIpAddress"]},
                        "azure": {},
                        "title": "Public IP Address"},
  "private_ip_address": {"aws": {"key": ["PrivateIpAddress"]},
                         "azure": {},
                         "title": "Private IP Address"},
  "product_codes": {"aws": {"key": ["ProductCodes"]},
                    "azure": {},
                    "title": "ProductCodes"},
  "vpc_id": {"aws": {"key": ["VpcId"]},
             "azure": {},
             "title": "VPC ID"},

  "state_transition_reason": {"aws": {"key": ["StateTransitionReason"]},
                              "azure": {},
                              "title": "State Transition Reason"},
  "id": {"aws": {"key": ["InstanceId"]},
         "azure": {},
         "title": "ID"},
  "name": {"aws": {"key": ["Tags"]},
           "azure": {},
           "title": "Name"},
  "ena_support": {"aws": {"key": ["EnaSupport"]},
                  "azure": {},
                  "title": "ENA Support"},
  "image_id": {"aws": {"key": ["ImageId"]},
               "azure": {},
               "title": "Image ID"},

  "private_dns_name": {"aws": {"key": ["PrivateDnsName"]},
                       "azure": {},
                       "title": "Private DNS Name"},

  "key_name": {"aws": {"key": ["KeyName"]},
               "azure": {},
               "title": "Key Name"},

  "security_groups": {"aws": {"key": ["SecurityGroups"]},
                      "azure": {},
                      "title": "Security Groups"},

  "client_token": {"aws": {"key": ["ClientToken"]},
                   "azure": {},
                   "title": "Client Token"},

  "subnet_id": {"aws": {"key": ["SubnetId"]},
                "azure": {},
                "title": "Subnet ID"},

  "type": {"aws": {"key": ["InstanceType"]},
           "azure": {},
           "title": "Class"},

  "source_dest_check": {"aws": {"key": ["SourceDestCheck"]},
                        "azure": {},
                        "title": "Source Dest Check"},

  "placement": {"aws": {"key": ["Placement", "AvailabilityZone"]},
                "azure": {},
                "title": "Placement"},
  "hypervisor": {"aws": {"key": ["Hypervisor"]},
                 "azure": {},
                 "title": "Hypervisor"},
  "architecture": {"aws": {"key": ["Architecture"]},
                   "azure": {},
                   "title": "Architecture"},
  "root_device_type": {"aws": {"key": ["RootDeviceType"]},
                       "azure": {},
                       "title": "Root Device Type"},
  "root_device_name": {"aws": {"key": ["RootDeviceName"]},
                       "azure": {},
                       "title": "Root Device Name"},

  "virtualization_type": {"aws": {"key": ["VirtualizationType"]},
                          "azure": {},
                          "title": "Virtualization Type"},
  "tags": {"aws": {"key": ["Tags"]},
           "azure": {},
           "title": "Tags"},
  "launch_index": {"aws": {"key": ["AmiLaunchIndex"]},
                   "azure": {},
                   "title": "AmiLaunchIndex"},

  "computer_name": {"aws": {},
           "azure": {"key": ["os_profile","computer_name"]},
           "title": "Computer Name"},
  "admin_username": {"aws": {},
           "azure": {"key": ["os_profile","admin_username"]},
           "title": "Admin User"},
"provisioning_state": {"aws": {},
           "azure": {"key": ["provisioning_state"]},
           "title": "Provisioning State"},
"resource_group": {"aws": {},
            "azure": {},
            "title": "Resource Group"},


}

pg_list_dict = {
  "id": {"aws": {"key": ["DBInstanceArn"]},
         "azure": {},
         "title": "ID"},

  "instance": {"aws": {"key": ["DBInstanceIdentifier"]},
               "azure": {},
               "title": "DBInstanceIdentifier"},
  "user": {"aws": {"key": ["MasterUsername"]},
           "azure": {},
           "title": "MasterUsername"},
  "dbname": {"aws": {"key": ["DBName"]},
             "azure": {},
             "title": "DBName"},
  "db_class": {"aws": {"key": ["DBInstanceClass"]},
               "azure": {},
               "title": "DBInstanceClass"},
  "engine_version": {"aws": {"key": ["EngineVersion"]},
                     "azure": {},
                     "title": "EngineVersion"},
  "host": {"aws": {"key": ["Endpoint", "Address"]},
           "azure": {},
           "title": "Host"},

  "status": {"aws": {"key": ["DBInstanceStatus"]},
             "azure": {},
             "title": "Status"},

  "region": {"aws": {},
             "azure": {},
             "title": "Region"},

  "port": {"aws": {"key": ["Endpoint", "Port"]},
           "azure": {},
           "title": "Port"},

  "storage_allocated": {"aws": {"key": ["AllocatedStorage"]},
                        "azure": {},
                        "title": "AllocatedStorage"},

  "engine": {"aws": {"key": ["Engine"]},
             "azure": {},
             "title": "Engine"},
  "arn": {"aws": {"key": ["DBInstanceArn"]},
          "azure": {},
          "title": "DBInstanceArn"},
  "auto_minor_upgrade": {"aws": {"key": ["AutoMinorVersionUpgrade"]},
                         "azure": {},
                         "title": "AutoMinorVersionUpgrade"},
  "create_time": {"aws": {"key": ["InstanceCreateTime"]},
                  "azure": {},
                  "title": "InstanceCreateTime"},
  "iops": {"aws": {"key": ["Iops"]},
           "azure": {},
           "title": "Iops"},
  "maint_window": {"aws": {"key": ["PreferredMaintenanceWindow"]},
                   "azure": {},
                   "title": "PreferredMaintenanceWindow"},
  "backup_window": {"aws": {"key": ["PreferredBackupWindow"]},
                    "azure": {},
                    "title": "PreferredBackupWindow"},
  "backup_retention": {"aws": {"key": ["BackupRetentionPeriod"]},
                       "azure": {},
                       "title": "BackupRetentionPeriod"},
  "latest_restorable": {"aws": {"key": ["LatestRestorableTime"]},
                        "azure": {},
                        "title": "LatestRestorableTime"},
  "az_is_multi": {"aws": {"key": ["MultiAZ"]},
                  "azure": {},
                  "title": "MultiAZ"},
  "az_primary": {"aws": {"key": ["AvailabilityZone"]},
                 "azure": {},
                 "title": "AvailabilityZone"},
  "az_secondary": {"aws": {"key": ["SecondaryAvailabilityZone"]},
                   "azure": {},
                   "title": "SecondaryAvailabilityZone"},
  "publicly_accessible": {"aws": {"key": ["PubliclyAccessible"]},
                          "azure": {},
                          "title": "PubliclyAccessible"},
  "monitoring_interval": {"aws": {"key": ["MonitoringInterval"]},
                          "azure": {},
                          "title": "MonitoringInterval"},

  "monitoring_resource_arn": {"aws": {"key": ["EnhancedMonitoringResourceArn"]},
                              "azure": {},
                              "title": "EnhancedMonitoringResourceArn"},
  "monitoring_role_arn": {"aws": {"key": ["MonitoringRoleArn"]},
                          "azure": {},
                          "title": "MonitoringRoleArn"},

  "subnet_group": {"aws": {"key": ["DBSubnetGroup", "DBSubnetGroupName"]},
                   "azure": {},
                   "title": "DBSubnetGroup"},

  "vpc_id": {"aws": {"key": ["DBSubnetGroup", "VpcId"]},
             "azure": {},
             "title": "VpcId"},

  "storage_encrypted": {"aws": {"key": ["StorageEncrypted"]},
                        "azure": {},
                        "title": "StorageEncrypted"},
  "storage_type": {"aws": {"key": ["StorageType"]},
                   "azure": {},
                   "title": "StorageType"},
  "vpc": {"aws": {"key": ["DBSubnetGroup", "VpcId"]},
          "azure": {},
          "title": "VPC"},
  "resource_group": {"aws": {},
            "azure": {},
            "title": "Resource Group"},
}

