# Generated by Django 2.0 on 2017-12-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booktable2',
            fields=[
                ('bookid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('booktitle', models.CharField(max_length=40)),
                ('bookauthor', models.CharField(max_length=40)),
                ('bookcheckedout', models.BooleanField(default=False)),
                ('bookduedate', models.DateTimeField(null=True)),
                ('userbookfine', models.FloatField(default=0, null=True)),
                ('userid', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usertable2',
            fields=[
                ('userid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('usertype', models.CharField(default='S', max_length=1)),
                ('userpassword', models.CharField(max_length=6)),
                ('userfirstname', models.CharField(max_length=20)),
                ('usermiddlename', models.CharField(max_length=20, null=True)),
                ('userlastname', models.CharField(max_length=20)),
            ],
        ),
    ]
