# Generated by Django 2.0 on 2017-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable2',
            name='bookduedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='userid',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
