# Generated by Django 2.0 on 2017-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20171227_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable2',
            name='bookduedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
