# Generated by Django 2.0 on 2017-12-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20171227_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable2',
            name='booktitle',
            field=models.CharField(max_length=100),
        ),
    ]
