# Generated by Django 2.0 on 2017-12-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20171227_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable2',
            name='userpassword',
        ),
    ]
