# Generated by Django 2.0 on 2017-12-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_remove_usertable2_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable2',
            name='userpassword',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
