# Generated by Django 2.0 on 2017-12-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_usertable2_userpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable2',
            name='userpassword',
        ),
    ]
