# Generated by Django 2.0 on 2017-12-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_remove_usertable2_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable2',
            name='userbookcheckoutdayslimit',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='usertable2',
            name='userbookcheckoutlimit',
            field=models.IntegerField(default=3, max_length=1),
        ),
    ]
