# Generated by Django 2.0 on 2017-12-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_auto_20171228_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable2',
            name='userbookcheckoutlimit',
            field=models.IntegerField(default=3),
        ),
    ]
