# Generated by Django 2.0 on 2017-12-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_auto_20171228_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable2',
            name='ischeckedout',
            field=models.CharField(default='IN', max_length=3),
        ),
    ]
