# Generated by Django 2.0 on 2017-12-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_usertable2_ischeckedout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable2',
            name='ischeckedout',
        ),
    ]
