# Generated by Django 2.0 on 2017-12-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_remove_usertable2_ischeckedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable2',
            name='hasoverduebooks',
            field=models.BooleanField(default=False),
        ),
    ]
