# Generated by Django 2.0 on 2017-12-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_auto_20171229_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable2',
            name='userbookfine',
        ),
        migrations.AddField(
            model_name='usertable2',
            name='userbookfine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
