# Generated by Django 2.0 on 2017-12-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_auto_20171229_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable2',
            name='checkedoutdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktable2',
            name='daysuntildue',
            field=models.IntegerField(null=True),
        ),
    ]
