# Generated by Django 2.0 on 2018-01-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_auto_20171230_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktable2',
            options={'verbose_name_plural': 'Catalog Of Books'},
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='userlastname',
            new_name='user_last_name',
        ),
    ]
