# Generated by Django 2.0 on 2018-01-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_auto_20180101_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable2',
            old_name='bookauthor',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='booktable2',
            old_name='bookcheckedout',
            new_name='book_checked_out',
        ),
        migrations.RenameField(
            model_name='booktable2',
            old_name='bookduedate',
            new_name='book_due_date',
        ),
        migrations.RenameField(
            model_name='booktable2',
            old_name='bookid',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='booktable2',
            old_name='booktitle',
            new_name='book_title',
        ),
        migrations.RenameField(
            model_name='booktable2',
            old_name='checkedoutdate',
            new_name='checked_out_date',
        ),
        migrations.RenameField(
            model_name='booktable2',
            old_name='daysuntildue',
            new_name='days_until_due',
        ),
        migrations.RenameField(
            model_name='booktable2',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='hasoverduebooks',
            new_name='has_overdue_books',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='userbookcheckoutdayslimit',
            new_name='user_book_check_out_days_limit',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='userbookcheckoutlimit',
            new_name='user_book_checkout_limit',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='userbookfine',
            new_name='user_book_fine',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='userfirstname',
            new_name='user_first_name',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='usermiddlename',
            new_name='user_middle_name',
        ),
        migrations.RenameField(
            model_name='usertable2',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
