# Generated by Django 2.0 on 2018-01-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0017_auto_20180101_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable2',
            name='book_checked_out',
        ),
        migrations.AddField(
            model_name='booktable2',
            name='in_library',
            field=models.BooleanField(default=True),
        ),
    ]
