# Generated by Django 2.0 on 2018-01-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0018_auto_20180101_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable2',
            name='user_book_fine',
        ),
    ]
