# Generated by Django 2.0 on 2018-01-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0020_remove_usertable2_has_overdue_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable2',
            name='user_type',
            field=models.CharField(choices=[('S', 'S'), ('F', 'F')], default='S', max_length=1),
        ),
    ]
