# Generated by Django 2.0 on 2018-01-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0022_auto_20180102_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable2',
            name='book_author',
            field=models.CharField(help_text='*required', max_length=40),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='book_due_date',
            field=models.DateField(blank=True, help_text='*yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='book_id',
            field=models.CharField(help_text='*required', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='book_title',
            field=models.CharField(help_text='*required', max_length=100),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='checked_out_date',
            field=models.DateField(blank=True, help_text='*yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='days_until_due',
            field=models.IntegerField(blank=True, help_text='Automatically calculated, you do not have to enter in this field.', null=True),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='in_library',
            field=models.BooleanField(default=True, help_text='*required'),
        ),
        migrations.AlterField(
            model_name='booktable2',
            name='user_id',
            field=models.CharField(blank=True, default='INLIBR', help_text='ID of user that has checked out this book', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_book_check_out_days_limit',
            field=models.IntegerField(choices=[(7, 7), (14, 14)], default=7, help_text='7 is standard for Students, 14 is standard for Faculty.'),
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_book_checkout_limit',
            field=models.IntegerField(choices=[(3, 3), (5, 5)], default=3, help_text='3 is standard for Students, 5 is standard for Faculty.'),
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_first_name',
            field=models.CharField(help_text='*required', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_id',
            field=models.CharField(help_text='*required', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_last_name',
            field=models.CharField(help_text='*required', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_type',
            field=models.CharField(choices=[('S', 'S'), ('F', 'F')], default='S', help_text='"S" Indicates Student, "F" Indicates Faculty.', max_length=1),
        ),
    ]
