# Generated by Django 2.0 on 2018-01-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0023_auto_20180102_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable2',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='usertable2',
            name='user_id',
            field=models.CharField(help_text='*required. first 3 letters of last name, number of last name ex: Bill Gates would be gat001, then if there was another person with the last name Gates, that person would be gat002', max_length=6, primary_key=True, serialize=False),
        ),
    ]
