# Generated by Django 2.0 on 2018-01-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0024_auto_20180104_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable2',
            name='user_id',
            field=models.ForeignKey(default='INLIBR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.usertable2'),
        ),
    ]
