@echo off
set PGHOME=c:\ETHANP~1\bigsql\pg10
set PGDATA=c:\ETHANP~1\bigsql\data\pg10
set PATH=c:\ETHANP~1\bigsql\pg10\bin;%PATH%
set PGUSER=postgres
set PGDATABASE=postgres
set PGPORT=5432
set PGPASSFILE=C:\Users\price\AppData\Roaming\postgresql\pgpass.conf
set PYTHONPATH=c:\ETHANP~1\bigsql\pg10\python\site-packages
set GDAL_DATA=c:\ETHANP~1\bigsql\pg10\share\gdal
